version: '3.8'
services:
  game-api:
    build:
      context: ./
      target: development
      args:
        SERVICE_NAME: 'game-api'
    restart: 'on-failure'
    depends_on:
      - db
    volumes:
      - .:/workdir
    ports:
      - 3000:3000
      - 9229:9229
    environment:
      PORT: 3000
      APP_ENV: local
  db:
    image: postgres:13-bullseye
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: Pa$$w0rd
      POSTGRES_DB: wizemoon
      POSTGRES_HOST_AUTH_METHOD: trust
  db-adminer:
    image: adminer
    ports:
      - 8080:8080
